name: Deploy to Production

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-gitlab-pipeline:
    name: Run gitlab pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Trigger gitlab
        uses: wei/curl@v1
        with:
          args: -X POST -F token=${{ secrets.GITLAB_DEPLOY_SECRET }} -F ref=main -F variables[REMOTE_COMMIT]=${GITHUB_SHA} -F variables[GITHUB_REMOTE_BRANCH]=${{ steps.extract_branch.outputs.branch }} -F variables[DEPLOY_TO]=prod https://gitlab.k-transfers.com/api/v4/projects/36/trigger/pipeline
