name: Deploy to Dev

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  run-gitlab-pipeline:
    name: Run gitlab pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Trigger gitlab
        uses: wei/curl@v1
        with:
          args: -X POST -F token=${{ secrets.GITLAB_DEPLOY_SECRET }} -F ref=main -F variables[REMOTE_COMMIT]=${GITHUB_SHA} -F variables[DEPLOY_TO]=dev https://gitlab.k-transfers.com/api/v4/projects/36/trigger/pipeline
